### PR TITLE
new

### PR DESCRIPTION
**Pull request by Gursimrancoder1208**
Does this pull request address a current issue or idea in Contributing.md?

Tell us what you did!

Do you hav

[gss.txt](https://github.com/JackMiranda/herms/files/3794842/gss.txt)

e any questions? :)

### CODE REVIEW

**Comment by langston-barrett** [comment]
The git history on this PR seems very messed up, so it's hard to tell what has been done. Please try putting your changes onto a clean branch and re-submitting. Thank you!

**Comment by Adrijaned** [comment]
@langston-barrett Please mark this invalid, looks like a last-time Hacktoberfest attempt

**Comment by langston-barrett** [comment]
@Adrijaned I don't understand. What does it mean to mark a PR as invalid?

**Comment by Adrijaned** [comment]
@langston-barett Assign it a label named `invalid`, you can get more info at https://hacktoberfest.digitalocean.com/faq

**Pull request closed without merging**
