### PR TITLE
Add --convert to edit subcommand, to load the recipe in with converte…

### PR DESCRIPTION
**Pull request by grault**
…d units, ready to save

Hi, I'd like to weigh in with regards to issue JackMiranda/herms#40 (found on up-for-grabs), or at least offer you an alternative. It's a pretty small change, so I just did it without communicating on the issue itself.

I had this idea of orthogonality in mind when I thought to myself: changing the unit of a recipe is basically editing. So I approached the use case from the direction of the "edit" subcommand, I borrowed the --convert option from "view" and added it to edit, which then loads up the recipe with converted units, so the user could just save it in case there are no other changes he/she wants.

I also was thinking about adding an option like --autosave, which I'm happy to write if you like. It wouldn't open up the editor, but save the recipe with the changed units.

What do you think?

Thanks,
Sza

### CODE REVIEW

**Comment by langston-barrett** [comment]
@grault Thanks, this looks like a good approach! I'll test it when I have a minute.

**Comment by grault** [comment]
@langston-barrett thanks for giving this some of your attention.. I also would be happy to polish things up (eg updating README.md if needed, etc). Let me know.

**Comment by grault** [comment]
Do you have any update on this?

**Comment by langston-barrett** [comment]
@grault Thanks for your patience. I'm on vacation now so I finally had a moment to review, and it works great!

**Pull request merged**
